language: ruby
sudo: false

cache: bundler

bundler_args: --no-deployment --binstubs=./bin

before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler

install:
  - bundle install --path vendor/bundle

script: bundle exec rspec

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.1
  - jruby-9.0.5.0
